# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://jornshen.cn
date_format: "ordinal"
title: JornShen
subtitle: "星光璀灿"
description: "沈灿辉的个人博客"
keywords: 星光璀灿, canhui shen, jornshen, jornshen
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: jornshen
organization: xmu
organization_url: http://www.xmu.edu.cn/
location: xmu, China
email: jorhshen@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: jornshen/jornshen.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: jornshen
#douban_username: freedim
#facebook_username: mzlogin
#weibo_username: mzlogin
#zhihu_username: mzlogin
#twitter_username: mzlogin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: gqnxide
disqus_username: jornshen 
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C, Python]
skill_technological_framework_keywords: [Redis, j2ee, Git, mysql]
hobbies_keywords: [Swim, Running, Handwriting, Music, Martial Art, Chess]
